name = "FTPClient"
uuid = "01fcc997-4f28-56b8-8a06-30002c134abb"
version = "1.0.1"

[deps]
LibCURL = "b27032c2-a3e7-50c8-80cd-2d36dbcbfd21"
URIParser = "30578b45-9adc-5946-b283-645ec420af67"

[compat]
LibCURL = ">= 0.5.1"
julia = "0.7, 1.0"

[extras]
FTPServer = "9c2b0ca7-0fb3-5789-8f1a-7604e426024c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["FTPServer", "Test"]
